  language: python

  python:
      - "3.6"
      - "3.7"
      - "3.8"

  os:
      - windows
      - linux

  install:
      pip install pillow
      pip install pfx
  
  script:
    - pytest
